name: PR tests

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build.outputs.image-uri }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node version
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
  lint:
    name: Linter
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: ${{ needs.install.outputs.image }}
    steps:
      - run: npm run lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: ${{ needs.install.outputs.image }}
    steps:
      - run: npm run test
  build:
    name: Build application
    runs-on: ubuntu-latest
    needs: [install]
    container:
      image: ${{ needs.install.outputs.image }}
    steps:
      - run: npm run build
  # TODO:
  # publish:
  #   name: Publish to NPM
  #   runs-on: ubuntu-latest
  #   needs: [lint, test, build]
  #   steps:
  #     - run: npm run dist
  #     - run: bash scripts/publish.sh
